### ISSUE TITLE
Update the COC to latest version

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/.github#2]
We have adopted the COC from Contribute Covenant

This current COC is the older version, you can update the file to the latest version of the contributor covenant code of conduct and submit a PR. 

https://www.contributor-covenant.org/version/2/1/code_of_conduct/

Also, you can add the latest COC file in the community repo by submitting a PR [here](https://github.com/openprivacytech/community)

**Comment by tripur3121** [comment]
@souravcipher I am submitting a PR but before that, I wanted to confirm that you want an exact copy of the Contributor Covenant.

**Comment by souravcipher** [comment]
Hi @tripur3121, yeah just copy the markdown format and replace the contact email from the existing COC.
